import os
from claude_api import run_claude_prompt
from github_release import create_github_release

def main():
    prompt_path = "super_prompt.txt"
    output_dir = "arturia_full_output"

    os.makedirs(output_dir, exist_ok=True)

    with open(prompt_path, "r") as f:
        full_prompt = f.read()

    print("[Claude Agent] Running full OSRS Super Prompt build...")
    run_claude_prompt(full_prompt, output_dir)

    if not os.path.exists(f"{output_dir}/README.txt"):
        with open(f"{output_dir}/README.txt", "w") as f:
            f.write("Placeholder: No output was generated by Claude.")

    create_github_release(output_dir, "Arturia_Full_Build")

if __name__ == "__main__":
    main()
