[build]
builder = "railpack"
buildCommand = "npm install"

[deploy]
startCommand = "node agent/index.js"

[env]
CLAUDE_API_KEY = "your-claude-api-key"
GITHUB_TOKEN = "your-github-token"
REPO_OWNER = "TRIDxNT"
REPO_NAME = "Base"